"""user data

Revision ID: 1fe2298b43c2
Revises: 46a43f993daa
Create Date: 2024-12-16 22:58:50.540415

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1fe2298b43c2'
down_revision = '46a43f993daa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('otp', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_data', mysql.JSON(), nullable=True))

    with op.batch_alter_table('product_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_images_product_id'), ['product_id'], unique=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_jenis_hewan'), ['jenis_hewan'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_kategori'), ['kategori'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_kategori'))
        batch_op.drop_index(batch_op.f('ix_products_jenis_hewan'))

    with op.batch_alter_table('product_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_images_product_id'))

    with op.batch_alter_table('otp', schema=None) as batch_op:
        batch_op.drop_column('user_data')

    # ### end Alembic commands ###
