"""Add seller table

Revision ID: 3948ad8f51fa
Revises: ecd02bbf7de6
Create Date: 2024-12-09 21:24:12.992654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3948ad8f51fa'
down_revision = 'ecd02bbf7de6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shop_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_seller', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_seller')

    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('shop_description')

    # ### end Alembic commands ###
