"""Add ProductImage table and relationship with Product

Revision ID: 46a43f993daa
Revises: 6e24c2bd4d83
Create Date: 2024-12-13 22:15:25.487376

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '46a43f993daa'
down_revision = '6e24c2bd4d83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('gambar')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gambar', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True))

    # ### end Alembic commands ###
