"""Add dimensions and weight columns to products

Revision ID: 6e24c2bd4d83
Revises: a901e0395c61
Create Date: 2024-12-13 20:51:27.350194

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6e24c2bd4d83'
down_revision = 'a901e0395c61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('berat', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('panjang', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('lebar', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tinggi', sa.Float(), nullable=True))

    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=50),
               type_=sa.String(length=20),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(collation='utf8mb4_general_ci', length=50),
               nullable=True)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('tinggi')
        batch_op.drop_column('lebar')
        batch_op.drop_column('panjang')
        batch_op.drop_column('berat')

    # ### end Alembic commands ###
