"""Remove nama column from users

Revision ID: e789a730b858
Revises: 89f88b1e64ce
Create Date: 2024-12-06 19:35:23.825560

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e789a730b858'
down_revision = '89f88b1e64ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('nama')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nama', mysql.VARCHAR(collation='utf8mb4_general_ci', length=100), nullable=False))

    # ### end Alembic commands ###
