"""Add Address and Bank models

Revision ID: fe2dadc5df2a
Revises: e789a730b858
Create Date: 2024-12-07 09:48:59.443540

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fe2dadc5df2a'
down_revision = 'e789a730b858'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto_profil', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('no_tlp', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
        batch_op.drop_column('last_login')
        batch_op.drop_column('no_tlp')
        batch_op.drop_column('foto_profil')

    # ### end Alembic commands ###
